UPLOADFILES:
  dataset_files:
    REPEAT: '+'
  schema_file:
    REPEAT: '1'
  solution_files:
    REPEAT: '+'

METADATA:
  solution_group:
    REPEAT+:
      solution_file_path:
        TEXT_MATCHER+: .+
      dataset_file_path:
        TEXT_MATCHER+: .+
  schema_file_path: .+