UPLOADFILES:
  dataset_files:
    REPEAT: '+'
  schema_file:
    REPEAT: '1'
  java_class_files:
    REPEAT: '+'

METADATA:
  solution_group:
    REPEAT+:
      java_method_name:
        TEXT_MATCHER+: .+
      dataset_file_path:
        TEXT_MATCHER+: .+
  java_class_files: 
    REPEAT+:
      java_file_path:
        TEXT_MATCHER: .+
      available_for_tests:
        OPTIONS:
          - true
          - false
  schema_file_path: .+
