UPLOADFILES:
  hooks:
    REPEAT: '?'

METADATA:
  tester_type: jdbc
  tester_name:
    TEXT_MATCHER: .+
  script_data:
    REPEAT+:
      runnable_group:
        REPEAT+:
          java_method_name: 
            TEXT_MATCHER: .+
          dataset_file_path:
            TEXT_MATCHER: .+
          tables:
            REPEAT*:
              table_name:
                TEXT_MATCHER: .+
              points:
                TEXT_MATCHER: \d+
                DEFAULT: '1'
          order_on:
            OPTIONS:
              - true
              - false
          points:
            TEXT_MATCHER: \d+
            DEFAULT: '1'
      enable_feedback_file_hook:
        OPTIONS:
          - true
          - false 
      feedback_file:
        TEXT_MATCHER: .*
      script_timeout:
        TEXT_MATCHER: \d+
        DEFAULT: "30"
      hooks_file_path:
        TEXT_MATCHER: .*